# Generated by Django 3.0.6 on 2022-04-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=16, null=True, verbose_name='昵称')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('email', models.CharField(blank=True, max_length=30, null=True, verbose_name='邮箱')),
                ('password', models.CharField(max_length=33, verbose_name='密码')),
                ('password_salt', models.CharField(default='eqwe./', max_length=6, verbose_name='密码加盐')),
                ('head_portrait', models.ImageField(upload_to='admin_portraits')),
                ('registered_ip_address', models.GenericIPAddressField(protocol='IPv4', verbose_name='注册IP')),
                ('last_ip', models.GenericIPAddressField(protocol='IPv4', verbose_name='最后登陆IP')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='最后登陆时间')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 't_admin',
            },
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdk', models.CharField(max_length=12)),
                ('state', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 't_code',
            },
        ),
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=16, null=True, verbose_name='昵称')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('email', models.CharField(blank=True, max_length=30, null=True, verbose_name='邮箱')),
                ('password', models.CharField(max_length=33, verbose_name='密码')),
                ('password_salt', models.CharField(default='eqwe./', max_length=6, verbose_name='密码加盐')),
                ('head_portrait', models.ImageField(upload_to='user_portraits')),
                ('registered_ip_address', models.GenericIPAddressField(protocol='IPv4', verbose_name='注册IP')),
                ('last_ip', models.GenericIPAddressField(protocol='IPv4', verbose_name='最后登陆IP')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='最后登陆时间')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 't_normal_user',
            },
        ),
    ]
