# Generated by Django 3.0.6 on 2022-04-04 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrator',
            options={'verbose_name': '管理员', 'verbose_name_plural': '管理员'},
        ),
        migrations.AlterModelOptions(
            name='code',
            options={'verbose_name': '激活码', 'verbose_name_plural': '激活码'},
        ),
        migrations.AlterModelOptions(
            name='normaluser',
            options={'verbose_name': '普通用户', 'verbose_name_plural': '普通用户'},
        ),
    ]
