# Generated by Django 3.0.6 on 2022-04-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220404_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluser',
            name='used_code',
            field=models.CharField(max_length=12, null=True, verbose_name='绑定激活码'),
        ),
    ]
