# Generated by Django 3.0.6 on 2022-04-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_normaluser_used_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='head_portrait',
            field=models.ImageField(blank=True, null=True, upload_to='admin_portraits'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='最后登陆IP'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='最后登陆时间'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='head_portrait',
            field=models.ImageField(blank=True, null=True, upload_to='user_portraits'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='最后登陆IP'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='最后登陆时间'),
        ),
    ]
